services:
  atlasdraw:
    build:
      context: .
    container_name: atlasdraw
    ports:
      - "3000:80"
    restart: on-failure
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 3
